// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjHvTjlqq9xIV4E_Qz6-Bhi51BythJRvA',
    appId: '1:282510672499:web:1ed4a9fd22eb2bb1eae006',
    messagingSenderId: '282510672499',
    projectId: 'project-a285d',
    authDomain: 'project-a285d.firebaseapp.com',
    storageBucket: 'project-a285d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD6kWsNLdkkPhxxsDlw6P3ewTSkd4YvTA',
    appId: '1:282510672499:android:91ee4fd15b07382deae006',
    messagingSenderId: '282510672499',
    projectId: 'project-a285d',
    storageBucket: 'project-a285d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDKcGI4I0SxvMb-cB8owDr4eRhZcZfSU4',
    appId: '1:282510672499:ios:3873d8036789678eeae006',
    messagingSenderId: '282510672499',
    projectId: 'project-a285d',
    storageBucket: 'project-a285d.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDKcGI4I0SxvMb-cB8owDr4eRhZcZfSU4',
    appId: '1:282510672499:ios:3873d8036789678eeae006',
    messagingSenderId: '282510672499',
    projectId: 'project-a285d',
    storageBucket: 'project-a285d.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjHvTjlqq9xIV4E_Qz6-Bhi51BythJRvA',
    appId: '1:282510672499:web:c520ccf0c208c0afeae006',
    messagingSenderId: '282510672499',
    projectId: 'project-a285d',
    authDomain: 'project-a285d.firebaseapp.com',
    storageBucket: 'project-a285d.firebasestorage.app',
  );
}
